apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: backend-reviews
        image: chaphe/backend-reviews-image:1.0
        ports:
        - containerPort: 3000
      - name: backend-catalog