apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-catalog-deploy
    labels:
        app: catalog-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: catalog-backend
    template:
        metadata:
            labels:
                app: catalog-backend
        spec:
            containers:
                - name: catalog-backend
                  image: chaphe/backend-catalog-image:1.0
                  ports:
                      - containerPort: 8081
                  env:
                      - name: MYSQL_DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-backend-config
                                key: mysql_db_host
                      - name: MYSQL_DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-backend-config
                                key: mysql_db_port
                      - name: MYSQL_DB_USERNAME
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-backend-config
                                key: mysql_db_username
                      - name: MYSQL_DB_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-backend-config
                                key: mysql_db_password
---
apiVersion: v1
kind: Service
metadata:
    name: catalog-backend-service
spec:
    type: NodePort
    selector:
        app: catalog-backend
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
          nodePort: 30300
