apiVersion: apps/v1
kind: Deployment
metadata:
    name: database-deployment
    labels:
        app: database
spec:
    replicas: 1
    selector:
        matchLabels:
            app: database
    template:
        metadata:
            labels:
                app: database
        spec:
            containers:
                - name: mongodb-reviews
                  image: mongo:5.0.0
                  env:
                      - name: MONGO_INITDB_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: mongodb-database
                                key: mongo_initdb_database
                  ports:
                      - containerPort: 27017
                  volumeMounts:
                      - name: mongo-initdb
                        mountPath: /docker-entrypoint-initdb.d
                - name: mysql-catalog
                  image: mysql:8.0.27
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-database
                                key: mysql_root_password
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-database
                                key: mysql_database
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-catalog-initdb
                        mountPath: /docker-entrypoint-initdb.d
                - name: mysql-store
                  image: mysql:8.0.27
                  ports:
                      - containerPort: 3306
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: store-database
                                key: mysql_root_password
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: store-database
                                key: mysql_database
                  volumeMounts:
                      - name: mysql-store-initdb
                        mountPath: /docker-entrypoint-initdb.d

            volumes:
                - name: mongo-initdb
                  configMap:
                      name: mongo-reviews-initdb-config
                - name: mysql-catalog-initdb
                  configMap:
                      name: mysql-catalog-initdb-config
                - name: mysql-store-initdb
                  configMap:
                      name: mysql-store-initdb-config
