apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-store-deployment
    labels:
        app: mongo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql-store
    template:
        metadata:
            labels:
                app: mysql-store
        spec:
            containers:
                - name: mysql
                  image: mysql:8.0.27
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-initdb
                        mountPath: /docker-entrypoint-initdb.d
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: store-database-config
                                key: mysql_root_password
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: store-database-config
                                key: mysql_database
            volumes:
                - name: mysql-initdb
                  configMap:
                      name: mysql-store-initdb-config
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-store-service
spec:
    type: ClusterIP
    selector:
        app: mysql-store
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-store-node-service
spec:
    type: NodePort
    selector:
        app: mysql-store
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
