apiVersion: v1
kind: Service
metadata:
    name: mongo-reviews-service
spec:
    type: ClusterIP
    selector:
        app: mongo-reviews
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-store-service
spec:
    type: ClusterIP
    selector:
        app: mysql-store
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-store-ext-service
spec:
    type: NodePort
    selector:
        app: mysql-store
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-catalog-service
spec:
    type: ClusterIP
    selector:
        app: mysql-catalog
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-catalog-ext-service
spec:
    type: NodePort
    selector:
        app: mysql-catalog
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: reviews-frontend-service
spec:
    type: NodePort
    selector:
        app: reviews-frontend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30201
