apiVersion: v1
kind: ConfigMap
metadata:
    name: mongodb-backend
data:
    mongodb_host: "mongodb-reviews"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-backend
data:
    mysql_db_host: "mysql-catalog-store"
    mysql_db_port: "3306"
    mysql_db_username: "root"
    mysql_db_password: "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: rabbitmq-backend
data:
    rabbitmq_host: "rabbitmq"
